[phases.setup]
nixPkgs = ["ffmpeg", "python310", "python310Packages.pip"]

[phases.install]
cmds = ["python -m venv /opt/venv", ". /opt/venv/bin/activate", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn wsgi:app"